### PR TITLE
Fe/fix/quests encounter

### LINKED ISSUE #26: Action card not updating
When a user clicks on an action card, it should update to the next progress level of the encounter.

### LINKED ISSUE #28: Hearts not updating
Hearts aren't currently updating to show encounter progress

### PR DESCRIPTION
**Pull request by okalimbet**
### Description
Display only one type of the quest on the page of available quests
If type of the quest is not available show a message to users
Hearts are dynamically fade with the quest progress
Add encounter number to a quest page
Users are redirected to Available quests page after completing the quest
Fix bug when encounter would not update when user clicks on the action card
Clean console.logs

### Screenshots
Screen Shot 2021-03-01 at 4 31 55 PM

### Changes include
- [x] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

### Checklist
- [ ] I have written tests for this code (happy & sad)
- [ ] I have updated the Readme
- [ ] I ran rubocop and fixed issues
- [ ] I ran full test suite - all tests passing

### CODE REVIEW

File: src/apiCalls.tsx [hunk 1]
```diff
@@ -11,6 +11,7 @@ const getData = (path: string) => {
 };
 
 const updateData = (path: string, action: string, data: object) => {
+  console.log("here is me in updateData" + " " + path + " " + action + " " + data)
```
Comment (CalebCyphers) [inline src/apiCalls.tsx]: Love these informative console.logs. we just need to remember to take them out

**Review by CalebCyphers — APPROVED** [review]
